### ISSUE TITLE
ftw.inflator 1.8.1 is not compatible with plone.app.multilingual 2.x

### ISSUE THREAD

**Issue by mbaechtold** [4teamwork/ftw.inflator#32]
One can no longer boot a project where `plone.app.multilingual` 2.0.2 and `ftw.inflator` 1.8.1 is installed. `ftw.inflator` 1.8.0 is working fine.

**Comment by jone** [comment]
What do you mean by `not compatible`? Do you get a traceback?

**Comment by mbaechtold** [comment]
@jone, sorry for the late answer. Here's the traceback:

```

**Comment by raphael-s** [comment]
@jone The release 1.8.1 has broken the compatibility of this package with 'plone.app.multilingual' or plone versions < 5
